config/routes.rb
Rails.application.routes.draw do

  root 'todos#index'

  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = TodoList.all
  end

  def new
    @todo = TodoList.new
  end

  def show
    @todo = TodoList.find(params[:id])
  end

  def edit
    @todo = TodoList.find(params[:id])
  end

  def create
    @todo = TodoList.new(todo_params)

    if @todo.save
      redirect_to todo_path
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h1>Todos#edit</h1>
<p>Find me in app/views/todos/edit.html.erb</p>

app/views/todos/index.html.erb
<h1>Todo List</h1>
<hr />

  <h2><%= todo.title %></h2>
  <% @todo_lists.each do |todo| %>
  <h3>
    <%= link_to page.title, page_path(page) %>
  </h3>
  <%end%>

  <p><%= @todo.description%></p>

<%else%>

  <h2>No Todo Items. Make a List!</h2>

<%end%>

<%= link_to 'New List Item', new_todo_path %>

app/views/todos/new.html.erb
<h1>New List Item</h1>

<%= form_for :todo do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true %>
  <br />
  <%= f.label :description %>
  <%= f.text_field :description, required: true %>
  <br />
  <%= f.label :complete %>
  <%= f.text_area :complete, required: true %>
  <br />
  <%= f.submit %>
<% end %>

<br />

<%= link_to 'Todo List', todos_path %>

app/views/todos/show.html.erb
<h1>Todos#show</h1>
<p>Find me in app/views/todos/show.html.erb</p>